// ISO-3 to ISO-2 mapping for common countries
export const ISO3_TO_ISO2: Record<string, string> = {
  USA: "US",
  GBR: "GB",
  DEU: "DE",
  FRA: "FR",
  ITA: "IT",
  ESP: "ES",
  NLD: "NL",
  BEL: "BE",
  POL: "PL",
  SWE: "SE",
  NOR: "NO",
  DNK: "DK",
  FIN: "FI",
  AUT: "AT",
  CHE: "CH",
  IRL: "IE",
  PRT: "PT",
  GRC: "GR",
  CZE: "CZ",
  HUN: "HU",
  ROU: "RO",
  BGR: "BG",
  HRV: "HR",
  SVK: "SK",
  SVN: "SI",
  LTU: "LT",
  LVA: "LV",
  EST: "EE",
  CAN: "CA",
  MEX: "MX",
  BRA: "BR",
  ARG: "AR",
  CHL: "CL",
  COL: "CO",
  PER: "PE",
  VEN: "VE",
  CHN: "CN",
  JPN: "JP",
  KOR: "KR",
  IND: "IN",
  AUS: "AU",
  NZL: "NZ",
  ZAF: "ZA",
  EGY: "EG",
  ISR: "IL",
  TUR: "TR",
  RUS: "RU",
  UKR: "UA",
  SAU: "SA",
  ARE: "AE",
  SGP: "SG",
  MYS: "MY",
  THA: "TH",
  IDN: "ID",
  PHL: "PH",
  VNM: "VN",
  PAK: "PK",
  BGD: "BD",
  IRN: "IR",
  IRQ: "IQ",
  JOR: "JO",
  LBN: "LB",
  KWT: "KW",
  OMN: "OM",
  QAT: "QA",
  BHR: "BH",
  MAR: "MA",
  TUN: "TN",
  DZA: "DZ",
  LBY: "LY",
  SDN: "SD",
  KEN: "KE",
  NGA: "NG",
  GHA: "GH",
  ETH: "ET",
  TZA: "TZ",
  UGA: "UG",
  ZWE: "ZW",
  NAM: "NA",
  BWA: "BW",
  MOZ: "MZ",
  AGO: "AO",
  CMR: "CM",
  CIV: "CI",
  SEN: "SN",
  MLI: "ML",
  BFA: "BF",
  NER: "NE",
  TCD: "TD",
  CAF: "CF",
  COG: "CG",
  COD: "CD",
  GAB: "GA",
  GNQ: "GQ",
  MWI: "MW",
  ZMB: "ZM",
  MDG: "MG",
  MUS: "MU",
  SYC: "SC",
  REU: "RE",
};

// Country name to ISO-2 mapping
export const COUNTRY_NAME_TO_ISO2: Record<string, string> = {
  "united states": "US",
  "united states of america": "US",
  "usa": "US",
  "united kingdom": "GB",
  "uk": "GB",
  "great britain": "GB",
  "england": "GB",
  "germany": "DE",
  "france": "FR",
  "italy": "IT",
  "spain": "ES",
  "netherlands": "NL",
  "holland": "NL",
  "belgium": "BE",
  "poland": "PL",
  "polska": "PL",
  "sweden": "SE",
  "norway": "NO",
  "denmark": "DK",
  "finland": "FI",
  "austria": "AT",
  "switzerland": "CH",
  "ireland": "IE",
  "portugal": "PT",
  "greece": "GR",
  "czech republic": "CZ",
  "czechia": "CZ",
  "hungary": "HU",
  "romania": "RO",
  "bulgaria": "BG",
  "croatia": "HR",
  "slovakia": "SK",
  "slovenia": "SI",
  "lithuania": "LT",
  "latvia": "LV",
  "estonia": "EE",
  "canada": "CA",
  "mexico": "MX",
  "brazil": "BR",
  "argentina": "AR",
  "chile": "CL",
  "colombia": "CO",
  "peru": "PE",
  "venezuela": "VE",
  "china": "CN",
  "japan": "JP",
  "south korea": "KR",
  "korea": "KR",
  "india": "IN",
  "australia": "AU",
  "new zealand": "NZ",
  "south africa": "ZA",
  "egypt": "EG",
  "israel": "IL",
  "turkey": "TR",
  "russia": "RU",
  "russian federation": "RU",
  "ukraine": "UA",
  "saudi arabia": "SA",
  "united arab emirates": "AE",
  "uae": "AE",
  "singapore": "SG",
  "malaysia": "MY",
  "thailand": "TH",
  "indonesia": "ID",
  "philippines": "PH",
  "vietnam": "VN",
  "pakistan": "PK",
  "bangladesh": "BD",
  "iran": "IR",
  "iraq": "IQ",
  "jordan": "JO",
  "lebanon": "LB",
  "kuwait": "KW",
  "oman": "OM",
  "qatar": "QA",
  "bahrain": "BH",
  "morocco": "MA",
  "tunisia": "TN",
  "algeria": "DZ",
  "libya": "LY",
  "sudan": "SD",
  "kenya": "KE",
  "nigeria": "NG",
  "ghana": "GH",
  "ethiopia": "ET",
  "tanzania": "TZ",
  "uganda": "UG",
  "zimbabwe": "ZW",
  "namibia": "NA",
  "botswana": "BW",
  "mozambique": "MZ",
  "angola": "AO",
  "cameroon": "CM",
  "ivory coast": "CI",
  "senegal": "SN",
  "mali": "ML",
  "burkina faso": "BF",
  "niger": "NE",
  "chad": "TD",
  "central african republic": "CF",
  "congo": "CG",
  "democratic republic of the congo": "CD",
  "gabon": "GA",
  "equatorial guinea": "GQ",
  "malawi": "MW",
  "zambia": "ZM",
  "madagascar": "MG",
  "mauritius": "MU",
  "seychelles": "SC",
  "reunion": "RE",
};

// ISO-2 to full country name
export const ISO2_TO_COUNTRY_NAME: Record<string, string> = {
  US: "United States",
  GB: "United Kingdom",
  DE: "Germany",
  FR: "France",
  IT: "Italy",
  ES: "Spain",
  NL: "Netherlands",
  BE: "Belgium",
  PL: "Poland",
  SE: "Sweden",
  NO: "Norway",
  DK: "Denmark",
  FI: "Finland",
  AT: "Austria",
  CH: "Switzerland",
  IE: "Ireland",
  PT: "Portugal",
  GR: "Greece",
  CZ: "Czech Republic",
  HU: "Hungary",
  RO: "Romania",
  BG: "Bulgaria",
  HR: "Croatia",
  SK: "Slovakia",
  SI: "Slovenia",
  LT: "Lithuania",
  LV: "Latvia",
  EE: "Estonia",
  CA: "Canada",
  MX: "Mexico",
  BR: "Brazil",
  AR: "Argentina",
  CL: "Chile",
  CO: "Colombia",
  PE: "Peru",
  VE: "Venezuela",
  CN: "China",
  JP: "Japan",
  KR: "South Korea",
  IN: "India",
  AU: "Australia",
  NZ: "New Zealand",
  ZA: "South Africa",
  EG: "Egypt",
  IL: "Israel",
  TR: "Turkey",
  RU: "Russia",
  UA: "Ukraine",
  SA: "Saudi Arabia",
  AE: "United Arab Emirates",
  SG: "Singapore",
  MY: "Malaysia",
  TH: "Thailand",
  ID: "Indonesia",
  PH: "Philippines",
  VN: "Vietnam",
  PK: "Pakistan",
  BD: "Bangladesh",
  IR: "Iran",
  IQ: "Iraq",
  JO: "Jordan",
  LB: "Lebanon",
  KW: "Kuwait",
  OM: "Oman",
  QA: "Qatar",
  BH: "Bahrain",
  MA: "Morocco",
  TN: "Tunisia",
  DZ: "Algeria",
  LY: "Libya",
  SD: "Sudan",
  KE: "Kenya",
  NG: "Nigeria",
  GH: "Ghana",
  ET: "Ethiopia",
  TZ: "Tanzania",
  UG: "Uganda",
  ZW: "Zimbabwe",
  NA: "Namibia",
  BW: "Botswana",
  MZ: "Mozambique",
  AO: "Angola",
  CM: "Cameroon",
  CI: "Ivory Coast",
  SN: "Senegal",
  ML: "Mali",
  BF: "Burkina Faso",
  NE: "Niger",
  TD: "Chad",
  CF: "Central African Republic",
  CG: "Congo",
  CD: "Democratic Republic of the Congo",
  GA: "Gabon",
  GQ: "Equatorial Guinea",
  MW: "Malawi",
  ZM: "Zambia",
  MG: "Madagascar",
  MU: "Mauritius",
  SC: "Seychelles",
  RE: "Reunion",
};
